version: '3.8'

services:
  # FastAPI приложение
  ngw_kadastr:
    container_name: nextgis_kad
    build: ./project
    volumes:
      - ./project:/usr/src/app
    ports:
      - "${WEB_PORT}:8000"
      - "${FLOWER_PORT}:5555"
    env_file:
      - .env
