version: '3.8'

services:
  # FastAPI приложение
  ngw_kadastr:
    container_name: nextgis_kad
    image: nextgis_kad:1.1.0
    volumes:
      - ./project/uploaded:/usr/src/app/uploaded
      - ./project/results:/usr/src/app/results
      - ./project/database:/usr/src/app/database
      - ./project/temp:/usr/src/app/temp
      - ./project/logs:/usr/src/app/logs
    ports:
      - "${WEB_PORT}:8000"
      - "${FLOWER_PORT}:5555"
    env_file:
      - .env